### ISSUE TITLE
selenium.commmon.exceptions.WebDriverException: Message: tab crashed

### ISSUE THREAD

**Issue by MacSnowDaddy** [MacSnowDaddy/airline_operation_watcher#2]
When I run these code on ec2 instance, selenium crashes with tab crashed message.

```
Exception in thread Thread-1 (scrape):
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/airline-ops/airline_operation_watcher/data_collector/data_collector_caller.py", line 30, in scrape
    collector = class_()
  File "/home/ec2-user/airline-ops/airline_operation_watcher/data_collector/data_collector.py", line 93, in __init__
    super().__init__()
  File "/home/ec2-user/airline-ops/airline_operation_watcher/data_collector/data_collector.py", line 31, in __init__
    self.browser = webdriver.Chrome()
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/ec2-user/.pyenv/versions/3.10.4/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: tab crashed
```

**Comment by MacSnowDaddy** [comment]
I don't know why detail, but when I changed the part i use thread, this issue was fixed.
see 186a4d848a838384560b65b203f16cb20a4944fd for detail.
